package analyzer

import (
	"fmt"
	"strings"

	"github.com/mvd-analyzer/mvd-analytics/result"
)

// This file exposes the analyzer DAG as an API-facing manifest (Stage 4 of
// PLAN-improve-analytics.md §5/§7). ArtifactManifest returns every node —
// eager and lazy — as plain data: name, tier, dependency edges, cost, and
// the top-level Result JSON key its artifact lands in. mvd-api serves it at
// GET /v1/artifacts and resolves the generic per-artifact endpoint through
// it (a closed registry: no user input reaches the filesystem beyond a name
// that ServableArtifact confirms). The same data drives the generated
// ARTIFACTS.md catalog and mvd-mcp's listArtifacts / getArtifact tools, so
// a new artifact becomes reachable everywhere without a hand-written tool.

// Cost levels — advisory, for API gating and docs. The one heavy pass is the
// lazy node (los); every eager node is light.
const (
	costLight = "light"
	costHeavy = "heavy"
)

// ArtifactMeta is one DAG node's public manifest entry.
type ArtifactMeta struct {
	Name        string   `json:"name"`
	Tier        string   `json:"tier"`        // "core" | "derived" | "post" | "lazy"
	Requires    []string `json:"requires"`    // artifact names this node reads
	Provides    []string `json:"provides"`    // artifact names this node writes (includes Name)
	Mutates     bool     `json:"mutates"`     // true for the in-place post-processors (Stage-2 debt)
	Lazy        bool     `json:"lazy"`        // materialised on demand, not in the eager bundle
	Cost        string   `json:"cost"`        // "light" | "heavy"
	ResultKey   string   `json:"resultKey"`   // top-level Result JSON key ("" = pseudo/internal, not served)
	Servable    bool     `json:"servable"`    // true when GET /v1/demos/{id}/artifacts/{name} serves it
	Description string   `json:"description"` // one-sentence contributor-facing summary
}

// metaFromSpec projects a nodeSpec into its public manifest entry. An
// artifact is servable when it lands in a Result section (ResultKey set) or
// is one of the two lazy artifacts materialised generically by mvd-api.
func metaFromSpec(s nodeSpec) ArtifactMeta {
	return ArtifactMeta{
		Name:        s.Name,
		Tier:        s.tier,
		Requires:    append([]string(nil), s.Requires...),
		Provides:    append([]string(nil), s.Provides...),
		Mutates:     s.Mutates,
		Lazy:        s.Lazy,
		Cost:        s.cost,
		ResultKey:   s.resultKey,
		Servable:    s.resultKey != "" || s.Lazy,
		Description: s.desc,
	}
}

// ArtifactManifest returns every DAG node — the eager pipeline nodes in
// registration order, then the lazy artifacts by name — as manifest data.
// It is static per binary (a pure function of the registered specs), so
// callers can cache it under an ETag keyed on the schema version. It mirrors
// ExportGraph's node set exactly.
func ArtifactManifest() []ArtifactMeta {
	specs := append(NewDefaultRegistry().specs, lazyArtifactSpecs()...)
	out := make([]ArtifactMeta, 0, len(specs))
	for _, s := range specs {
		out = append(out, metaFromSpec(s))
	}
	return out
}

// ServableArtifact returns the manifest entry for a servable artifact, or
// ok=false when the name is unknown or not servable. This is the closed
// registry mvd-api's generic endpoint resolves through — the name is matched
// against the manifest map, never joined into a filesystem path.
func ServableArtifact(name string) (ArtifactMeta, bool) {
	for _, m := range ArtifactManifest() {
		if m.Name == name && m.Servable {
			return m, true
		}
	}
	return ArtifactMeta{}, false
}

// ArtifactsMarkdown renders the artifact catalog as markdown (the committed
// mvd-analytics/ARTIFACTS.md). Deterministic — the same registered specs
// always produce byte-identical output, which a drift test pins. Regenerate
// with `make artifacts-md` (or `qw-analyze -artifacts-md`).
func ArtifactsMarkdown() string {
	var b strings.Builder
	b.WriteString("# Artifact catalog\n\n")
	b.WriteString("<!-- GENERATED by `qw-analyze -artifacts-md` (or `make artifacts-md`). Do not hand-edit. -->\n\n")
	b.WriteString("Every node in the analytics DAG, as declared in " +
		"[`analyzer/dag.go`](analyzer/dag.go) and [`analyzer/materialize.go`](analyzer/materialize.go). ")
	b.WriteString("This is the one document a contributor reads to add an analytic: pick the ")
	b.WriteString("artifacts you `requires`, declare what you `provides`, and the engine schedules, ")
	b.WriteString("caches, and serves it. See [`README.md`](README.md) for how to register a node.\n\n")

	b.WriteString("**Servable** artifacts are reachable at `GET /v1/demos/{id}/artifacts/{name}` ")
	b.WriteString("(and via the mvd-mcp `getArtifact` tool). Eager servable artifacts land in the ")
	b.WriteString("Result JSON under **resultKey**; the lazy artifact (`los`) ")
	b.WriteString("is materialised on demand. Non-servable nodes (`clock`, `roster`, `identity`, and ")
	b.WriteString("the in-place post-processors) are internal — they have no standalone Result key.\n\n")

	b.WriteString("| Artifact | Tier | Cost | Lazy | resultKey | Requires | Provides | Description |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|\n")
	for _, m := range ArtifactManifest() {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s | %s |\n",
			m.Name,
			m.Tier,
			m.Cost,
			yesNo(m.Lazy),
			codeOrDash(m.ResultKey),
			codeList(m.Requires),
			codeList(m.Provides),
			m.Description,
		)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "Generated at schema version %d.\n", result.CurrentSchemaVersion)
	return b.String()
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func codeOrDash(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + s + "`"
}

func codeList(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = "`" + it + "`"
	}
	return strings.Join(out, ", ")
}
